### ISSUE TITLE
Investigate error 

### ISSUE THREAD

**Issue by LMS007** [RapidAPI/testing-worker#22]
```
 ERROR  (steps || []) is not iterable                                                                                                      14:17:40

  at new TestExecutable (src/models/TestExecutable.js:37:28)
  at executeTest (src/RapidTest.js:9:18)
  at src/RapidTest.js:93:18
  at Array.map (<anonymous>)
  at fetchAndExecuteTests (src/RapidTest.js:87:20)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (internal/process/task_queues.js:93:5)
  at async executeOnce (src/main.js:138:5)
  at async Timeout._onTimeout (src/main.js:124:11)
  ```
  
  This error seems to happen after tests are executed

**Comment by LMS007** [comment]
moved to clickup
